### ISSUE TITLE
Map Section

### ISSUE THREAD

**Issue by Sessions21** [Sessions21/Project1-SAHM-Calendar#5]
Show map information for scheduling appointment locations.

**Comment by avlamakis** [comment]
Pushed into the develop branch the code placed within the HTML to display and format the map function. Reference link https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/ 
for code example.

**Comment by avlamakis** [comment]
Added CSS styling to the map container to not overflow into the footer. Need to create a new container to display map in center of page. Functionality of map and sizing are working great.

**Comment by avlamakis** [comment]
https://stackoverflow.com/questions/32571611/positioning-a-mapbox-leaflet-map-inside-a-container-div
referenced this link to help with display of map section
