### ISSUE TITLE
Weather Section

### ISSUE THREAD

**Issue by Sessions21** [Sessions21/Project1-SAHM-Calendar#6]
Create a weather section that displays multi day weather information to present to user for more informed scheduling.

**Comment by avlamakis** [comment]
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

**Comment by avlamakis** [comment]
Created the weather fetch for API, multiple commits for global variables, fetch, display, and event listener added

**Comment by avlamakis** [comment]
Updated index html with new script links  and display function within section to appear on page

**Comment by avlamakis** [comment]
Updated html with justify content to display weather forecast and current weather in center of page
