### ISSUE TITLE
Calendar/Schedule Section

### ISSUE THREAD

**Issue by Sessions21** [Sessions21/Project1-SAHM-Calendar#7]
Main section for scheduling daily appointments

**Comment by avlamakis** [comment]
Added Index HTML with script links and styling along with JavaScript code to retrieve the time and date while saving information listed on it. Need to reformat html with boot strap to fit more precisely on the page as it overflows and is not centered

**Comment by avlamakis** [comment]
Updated formatting of HTML to center content of calendar in middle of page, save functions updated to save task per click
